{% set name = "ansible-compat" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansible-compat-{{ version }}.tar.gz
  sha256: c2d0739c50aa5ebca1ce2eb4cbd27025723f55d267abbe6444a133c218ac37d6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.0
  run:
    - cached-property ~=1.5  # [py<=37]
    - python
    - pyyaml
    - subprocess-tee

test:
  imports:
    - ansible_compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible-community/ansible-compat
  summary: Ansible compatibility goodies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
