{% set name = "ansible-compat" %}
{% set version = "25.1.1" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b4e4609bb9b91588758be4d26ff25ff46d7ce83e6b8f2cc58cf77d736ec1f1ab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.0
    - setuptools
  run:
    - python >={{ python_min }}
    - ansible-core >=2.14
    - pyyaml
    - subprocess-tee >=0.4.1
    - packaging
    - jsonschema >=4.6.0
    - typing-extensions >=4.5.0

test:
  imports:
    - ansible_compat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ansible-community/ansible-compat
  summary: Ansible compatibility goodies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
