{% set name = "ansible-compat" %}
{% set version = "4.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansible-compat-{{ version }}.tar.gz
  sha256: 277dd6588c3d2e6c5c793e9d0517afef03da2e67631c6f7f8dde42f2631857da

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.0
  run:
    - python >=3.8
    - ansible-core >=2.12
    - pyyaml
    - subprocess-tee >=0.4.1
    - packaging
    - jsonschema >=4.6.0

test:
  imports:
    - ansible_compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible-community/ansible-compat
  summary: Ansible compatibility goodies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
