{% set name = "ansible-compat" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansible-compat-{{ version }}.tar.gz
  sha256: 4027da4ec2b524c263a801cc2dc6da2b98c2996cec258cef118a30c790467ed2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.0
  run:
    - cached-property ~=1.5  # [py<=37]
    - python
    - pyyaml
    - subprocess-tee

test:
  imports:
    - ansible_compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible-community/ansible-compat
  summary: Ansible compatibility goodies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
