{% set name = "ansible-compat" %}
{% set version = "26.9.0" %}
{% set python_min = "3.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e101649196e4fffc810c3f9f4f185107cc1e5be0ef26d38ad9c4abfa22b0b183

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.0
    - setuptools
  run:
    - python >={{ python_min }}
    - ansible-core >=2.18
    - pyyaml
    - subprocess-tee >=0.4.1
    - packaging
    - jsonschema >=4.6.0
    - typing-extensions >=4.5.0

test:
  imports:
    - ansible_compat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ansible-community/ansible-compat
  summary: Ansible compatibility goodies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
