{% set name = "ansible-compat" %}
{% set version = "24.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ad873e0dae8b2de79bc33ced813d6c92c716c4d7b82f9a4693e1fd57f43776e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.0
    - setuptools
  run:
    - python >={{ python_min }}
    - ansible-core >=2.14
    - pyyaml
    - subprocess-tee >=0.4.1
    - packaging
    - jsonschema >=4.6.0
    - typing-extensions >=4.5.0

test:
  imports:
    - ansible_compat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ansible-community/ansible-compat
  summary: Ansible compatibility goodies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
